/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import ObserverPattern.Schedule;
import SingletonPattern.Singletonn;
import StatePattern.Stay;
import Ui.FreeShedule.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lgpc
 */
public class FreeStay extends javax.swing.JFrame {

    /**
     * Creates new form FreeStay
     */
    Stay st = new Stay();

    String[] stayList; // 숙박시설 목록
    static int stayPrice; // 숙박시설 가격

    DefaultTableModel model;
    Singletonn si = Singletonn.getInstance();

    static int freemoney; // 자유여행 총합 가격
    int rnum = 1; // 객실 수

    public FreeStay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("숙박시설");
        setMinimumSize(new java.awt.Dimension(500, 310));
        setPreferredSize(new java.awt.Dimension(493, 253));
        getContentPane().setLayout(null);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "숙박시설을 선택해주세요." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 280, 160);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "게스트하우스", "호텔", "펜션", "리조트" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(10, 60, 113, 24);

        jButton1.setText("숙박 시설 선택");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 220, 127, 27);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(330, 50, 140, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/선택된 방 및 가격.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(311, 11, 160, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/객실 수에 따른 가격.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 130, 190, 40);

        jTextField3.setText("0");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 180, 168, 24);

        jTextField2.setText("1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 90, 47, 24);

        jButton4.setText("객실 수 입력");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(360, 90, 113, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/숙박시설.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 490, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String s = jComboBox2.getSelectedItem().toString(); // 선택된 숙박시설
        st.setState(s);// 선택된 숙박시설에 따른 상태
        this.stayList = st.getRoom(); // 선택된 숙박시설 목록
        jList1.setListData(stayList);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int c = jList1.getAnchorSelectionIndex(); // 객실 선택 번호
            this.stayPrice = st.getRoompice(c, this.rnum) * FreeShedule.days; //일정에 따른 객실 가격
            this.freemoney = stayPrice + si.getFreeMoney(); // 자유여행 총합 가격

            jTextField1.setText(stayList[c]);
            jTextField3.setText(stayPrice + "원");

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        si.setFreeMoney(freemoney); // 싱글턴에 총합 가격 저장
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String rnum = jTextField2.getText(); // 입력받은 객실 수
        this.rnum = Integer.parseInt(rnum);
        int c = jList1.getAnchorSelectionIndex(); // 객실 선택 번호

        this.stayPrice = st.getRoompice(c, this.rnum) * FreeShedule.days; //일정에 따른 객실 가격
        this.freemoney = stayPrice + si.getFreeMoney(); // 자유여행 총합 가격

        jTextField1.setText(stayList[c]);
        jTextField3.setText(stayPrice + "원");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FreeStay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FreeStay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FreeStay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FreeStay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FreeStay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
