/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import ObserverPattern.Schedule;
import SingletonPattern.Singletonn;
import StatePattern.Culture;
import StatePattern.Stay;
import StatePattern.Traffic;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lgpc
 */
public class FreeShedule extends javax.swing.JFrame {

    /**
     * Creates new form FreeShedule
     */
    static String poeple; // 인원수
    static String place; // 여행지
    static String startdays; // 출발 날짜
    static String returndays; // 복귀 날짜
    static String startmonth; // 출발 월 
    static String startday; // 출발 일
    static String returnmonth; // 복귀 월
    static String returnday; // 복귀 일
    static String m;
    static int poepleint; // 인원수
    static int startmonthint; // 출발 월
    static int startdayint; // 출발 일
    static int returnmonthint; // 복귀 월
    static int returndayint; // 복귀 일
    static int days; // 여행 일수

    Schedule schedule = new Schedule();
    Singletonn si = Singletonn.getInstance();
    DefaultTableModel model;

    public FreeShedule() {
        initComponents();
        jTextField4.setText(si.getFreeMoney() + "원");
        jTextField5.setText(si.getPacMoney() + "원");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 430));
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "서울", "대구", "제주", "도쿄", "파리" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(486, 16, 57, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/여행지_2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(428, 16, 51, 36);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/인원_2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(561, 16, 51, 36);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/일정 선택.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 10, 121, 40);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(17, 16, 122, 24);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/출발일_1.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 10, 63, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/복귀일_1.png"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 10, 71, 40);

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(149, 16, 50, 24);

        jTextField2.setText("0");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 16, 50, 24);

        jTextField3.setText("0");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(619, 16, 50, 24);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "일정", "출발일", "복귀일", "출발지", "여행지", "인원"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(17, 75, 800, 145);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(144, 339, 182, 24);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/자유여행 경비.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(7, 333, 130, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/패키지여행 경비.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(332, 333, 150, 40);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(489, 339, 182, 24);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("자유 여행"));
        jPanel1.setInheritsPopupMenu(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/교통 수단_1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/숙박 시설.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/축제.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton4)
                .addGap(46, 46, 46)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(17, 238, 446, 88);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("패키지 여행"));
        jPanel2.setInheritsPopupMenu(true);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/패키지 여행_1.png"))); // NOI18N
        jButton7.setBorder(new javax.swing.border.MatteBorder(null));
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(489, 238, 144, 91);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("기타 경비"));
        jPanel3.setInheritsPopupMenu(true);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/기타 경비_1.png"))); // NOI18N
        jButton8.setBorder(new javax.swing.border.MatteBorder(null));
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton8)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(665, 238, 150, 86);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/경비선택.png"))); // NOI18N
        jButton9.setText("경비 확인");
        jButton9.setBorder(new javax.swing.border.MatteBorder(null));
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(690, 330, 120, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/배경.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 840, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //입력 받은 값을 변수에 저장
        this.poeple = this.jTextField3.getText();
        this.place = (String) this.jComboBox1.getSelectedItem();
        this.startdays = this.jTextField1.getText();
        this.returndays = this.jTextField2.getText();
        this.startmonth = startdays.substring(0, 2);
        this.startday = startdays.substring(3, 5);
        this.returnmonth = returndays.substring(0, 2);
        this.returnday = returndays.substring(3, 5);

        //입력받은 값을 int형으로 변환
        this.startmonthint = Integer.parseInt(startmonth);
        this.startdayint = Integer.parseInt(startday);
        this.returnmonthint = Integer.parseInt(returnmonth);
        this.returndayint = Integer.parseInt(returnday);
        this.poepleint = Integer.parseInt(poeple);
        this.days = returndayint - startdayint + 1;

        //입력받은 값으로 일정 설정
        schedule.setdays(startmonthint, startdayint, returnmonthint, returndayint, poepleint, place);

        //일정 String형 설정
        //String startdays = this.startmonth+"월 "+this.startday+"일";
        //String returndays = this.returnmonth+"월 "+this.returnday+"일";
        String people = this.poeple + "명";

        //테이블에 일정 출력
        Object[] columns = {"일정", this.startdays, this.returndays, "부산", this.place, people};
        model = (DefaultTableModel) jTable1.getModel();
        model.addRow(columns);

        // 경비 초기화
        si.setFreeMoney(0);
        si.setPacMoney(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Date date = jDateChooser1.getDate(); // 출발일 설정
        DateFormat format1 = new SimpleDateFormat("MM/dd");
        jTextField2.setText(format1.format(date));
        System.out.println(format1.format(date));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date date = jDateChooser1.getDate(); // 도착일 설정
        DateFormat format1 = new SimpleDateFormat("MM/dd");
        jTextField1.setText(format1.format(date));
        System.out.println(format1.format(date));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FreeTraffic.main(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        FreeStay.main(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        CultureUi.main(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTextField4.setText(si.getFreeMoney() + "원");
        jTextField5.setText(si.getPacMoney() + "원");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        PackageUi.main(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        OtherJFrame.main(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //입력받은 값을 변수에 저장
        this.poeple = model.getValueAt(jTable1.getSelectedRow(), 5).toString().substring(0, model.getValueAt(jTable1.getSelectedRow(), 5).toString().length() - 1); // 테이블 인원 수
        this.place = model.getValueAt(jTable1.getSelectedRow(), 4).toString(); // 테이블 여행지
        this.startmonth = model.getValueAt(jTable1.getSelectedRow(), 1).toString().substring(0, 2); // 테이블 출발일;
        this.startday = model.getValueAt(jTable1.getSelectedRow(), 1).toString().substring(3, 5); // 테이블 출발일;
        this.returnmonth = model.getValueAt(jTable1.getSelectedRow(), 2).toString().substring(0, 2); // 테이블 출발일;
        this.returnday = model.getValueAt(jTable1.getSelectedRow(), 2).toString().substring(3, 5); // 테이블 출발일;

        //입력받은 값을 int형으로 변환
        this.startmonthint = Integer.parseInt(startmonth);
        this.startdayint = Integer.parseInt(startday);
        this.returnmonthint = Integer.parseInt(returnmonth);
        this.returndayint = Integer.parseInt(returnday);
        this.poepleint = Integer.parseInt(poeple);
        this.days = returndayint - startdayint + 1;

        // 경비 초기화
        si.setFreeMoney(0);
        si.setPacMoney(0);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FreeShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FreeShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FreeShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FreeShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FreeShedule().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
