/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import CompositePattern.Menu;
import CompositePattern.MenuDetail;
import CompositePattern.MenuComponent;
import CompositePattern.MenuDaegu;
import CompositePattern.MenuJeju;
import CompositePattern.MenuParis;
import CompositePattern.MenuSeoul;
import CompositePattern.MenuTokyo;
import IteratorPattern.CompositeIterator;
import ObserverPattern.Schedule;
import SingletonPattern.Singletonn;
import Ui.FreeShedule;
import java.awt.Component;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lgpc
 */
public class PackageUi extends javax.swing.JFrame {

    /**
     * Creates new form Package
     */
    FreeShedule fe = new FreeShedule();
    Schedule sc = fe.schedule;
    Singletonn si = Singletonn.getInstance();
    public static DefaultTableModel model1; // 패키지 목록 테이블

    //선택된 패키지,가격(String형, int형),패키지번호
    static String choicePackage;
    static String choicePackagePrice;
    static int choicePackagePriceint;
    static int packageNumber;

    //각 여행지 패키지 목록 생성
    MenuComponent DaeguMenu = new Menu("대구");
    MenuComponent SeoulMenu = new Menu("서울");
    MenuComponent TokyoMenu = new Menu("도쿄");
    MenuComponent JejuMenu = new Menu("제주");
    MenuComponent ParisMenu = new Menu("파리");
    MenuComponent allMenu = new Menu("전체");

    public PackageUi() {
        initComponents();
        model1 = (DefaultTableModel) jTable2.getModel();

        sc.setdays(fe.startmonthint, fe.startdayint, fe.returnmonthint, fe.returndayint, fe.poepleint, fe.place);

        // 여행지에 따른 패키지 상품 테이블에 출력
        if (fe.place == "대구") {
            DaeguMenu.print();
        } else if (fe.place == "서울") {
            SeoulMenu.print();
        } else if (fe.place == "제주") {
            JejuMenu.print();
        } else if (fe.place == "도쿄") {
            TokyoMenu.print();
        } else if (fe.place == "파리") {
            ParisMenu.print();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(745, 510));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/선택된 패키지 상품_2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 400, 180, 43);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 410, 140, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1인당 패키지 가격_1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 392, 200, 60);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(450, 410, 140, 27);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/패키지 선택.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 390, 120, 70);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "지역", "구성", "일정", "기본가격"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 690, 148);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 700, 106);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/배경_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        si.setPacMoney((choicePackagePriceint - (int) (choicePackagePriceint * 0.1)) * fe.poepleint);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        this.choicePackagePrice = model1.getValueAt(jTable2.getSelectedRow(), 3).toString().substring(0, model1.getValueAt(jTable2.getSelectedRow(), 3).toString().length() - 1);
        this.choicePackagePriceint = Integer.parseInt(choicePackagePrice);
        //상품 상세내역 설정
        if (fe.place == "대구") {
            jTextArea1.setText(DaeguMenu.getChild(jTable2.getSelectedRow()).getDetail());
        } else if (fe.place == "서울") {
            jTextArea1.setText(SeoulMenu.getChild(jTable2.getSelectedRow()).getDetail());
        } else if (fe.place == "제주") {
            jTextArea1.setText(JejuMenu.getChild(jTable2.getSelectedRow()).getDetail());
        } else if (fe.place == "도쿄") {
            jTextArea1.setText(TokyoMenu.getChild(jTable2.getSelectedRow()).getDetail());
        } else if (fe.place == "파리") {
            jTextArea1.setText(ParisMenu.getChild(jTable2.getSelectedRow()).getDetail());
        }
        jTextArea1.append("할인 10%\n");

        // 선택된 패키지 상품 이름 및 가격 출력
        jTextField1.setText(model1.getValueAt(jTable2.getSelectedRow(), 0).toString());
        jTextField2.setText(choicePackagePriceint - (int) (choicePackagePriceint * 0.1) + "원");
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackageUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
